os: linux
language: shell

services:
  - docker

addons:
  apt:
    packages:
    - jq

env:
  - ADDON=flicd ARCH=aarch64

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ./build.sh "$ADDON" "$ARCH"

# vim: set ft=yaml et ts=2 sw=2 :
